<h2>Import Library</h2>

In [ ]:
import pandas as pd
import numpy as np

Mount the csv files, we are using the pima diabetes csv to classify whether a patient has diabetes or not



In [ ]:
# We want to load our dataset from my personal gdrive, we cant do it normally (using pd.read_csv instantly), we need to connect our google collab with out
# gdrive using the drive library then we want to mount it. if we use jupyter notebook (local DS) we can just use read_csv, this is not possibly
# in google collab
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
# data =pd.read_csv("pima-indians-diabetes.csv")
data = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Tensorflow Pembelajaran Mandiri/Exercise/2. Classification with Logistic Regression Exercise/pima-indians-diabetes.csv')

<h2>Initial Data Cleaning</h2>

In [ ]:
data.isna().sum()

times_pregnant            0
glucose_concentration     0
blood_pressure            0
triceps_skin_thickness    0
serum_insulin             0
body_mass_index           0
diabetes_pedigree         0
age                       0
is_diabetes               0
dtype: int64

In [ ]:
data[data['is_diabetes'] > 1]

Empty DataFrame
Columns: [times_pregnant, glucose_concentration, blood_pressure, triceps_skin_thickness, serum_insulin, body_mass_index, diabetes_pedigree, age, is_diabetes]
Index: []

<h3>Average Data to fill in entries that has 0 value</h3>

In [ ]:
# Calculate the Average Values
ave_bloodpressure = data['blood_pressure'].mean()
ave_glu_cont = data['glucose_concentration'].mean()
ave_triceps = data['triceps_skin_thickness'].mean()
ave_body_mass_index = data['body_mass_index'].mean()
print(ave_bloodpressure)
print(ave_glu_cont)
print(ave_triceps)
print(ave_body_mass_index)

69.10546875
120.89453125
20.536458333333332
31.992578124999998


In [ ]:
data['body_mass_index']=data['body_mass_index'].replace(0,ave_body_mass_index)
data['triceps_skin_thickness']=data['triceps_skin_thickness'].replace(0,ave_triceps)
data['glucose_concentration']=data['glucose_concentration'].replace(0,ave_glu_cont)
data['blood_pressure']=data['blood_pressure'].replace(0,ave_bloodpressure)

<h3>Checking whether our changes are successful or not</h3>

In [ ]:

data[data['body_mass_index'] == 0]

Empty DataFrame
Columns: [times_pregnant, glucose_concentration, blood_pressure, triceps_skin_thickness, serum_insulin, body_mass_index, diabetes_pedigree, age, is_diabetes]
Index: []

In [ ]:
data[data['triceps_skin_thickness'] == 0]

Empty DataFrame
Columns: [times_pregnant, glucose_concentration, blood_pressure, triceps_skin_thickness, serum_insulin, body_mass_index, diabetes_pedigree, age, is_diabetes]
Index: []

In [ ]:
data[data['glucose_concentration'] == 0]

Empty DataFrame
Columns: [times_pregnant, glucose_concentration, blood_pressure, triceps_skin_thickness, serum_insulin, body_mass_index, diabetes_pedigree, age, is_diabetes]
Index: []

In [ ]:
data[data['blood_pressure'] == 0]

Empty DataFrame
Columns: [times_pregnant, glucose_concentration, blood_pressure, triceps_skin_thickness, serum_insulin, body_mass_index, diabetes_pedigree, age, is_diabetes]
Index: []

In [ ]:
data.sample(5)

times_pregnant  glucose_concentration  blood_pressure  \
408               8                  197.0            74.0   
113               4                   76.0            62.0   
100               1                  163.0            72.0   
509               8                  120.0            78.0   
640               0                  102.0            86.0   

     triceps_skin_thickness  serum_insulin  body_mass_index  \
408               20.536458              0             25.9   
113               20.536458              0             34.0   
100               20.536458              0             39.0   
509               20.536458              0             25.0   
640               17.000000            105             29.3   

     diabetes_pedigree  age  is_diabetes  
408              1.191   39            1  
113              0.391   25            0  
100              1.222   33            1  
509              0.409   64            0  
640              0.695   27            0

In [ ]:
data[data['is_diabetes'] > 1]

Empty DataFrame
Columns: [times_pregnant, glucose_concentration, blood_pressure, triceps_skin_thickness, serum_insulin, body_mass_index, diabetes_pedigree, age, is_diabetes]
Index: []

<h2>Check and Convert Datatype of each column</h2>

In [ ]:
data.dtypes

times_pregnant              int64
glucose_concentration     float64
blood_pressure            float64
triceps_skin_thickness    float64
serum_insulin               int64
body_mass_index           float64
diabetes_pedigree         float64
age                         int64
is_diabetes                 int64
dtype: object

<h3>Changing age Column, times_pregnant Column, is_diabetes Column into int64</h3>

In [ ]:
data.times_pregnant = data.times_pregnant.astype('int64')
data.age = data.age.astype('int64')
data.is_diabetes = data.is_diabetes.astype('int64')

In [ ]:
data.dtypes

times_pregnant              int64
glucose_concentration     float64
blood_pressure            float64
triceps_skin_thickness    float64
serum_insulin               int64
body_mass_index           float64
diabetes_pedigree         float64
age                         int64
is_diabetes                 int64
dtype: object

<h2>Normalisasi Data</h2>

In [ ]:
label = data.pop('is_diabetes')
label.sample(5)

133    0
381    0
566    0
143    1
485    1
Name: is_diabetes, dtype: int64

In [ ]:
# Melakukan normalisasi dengan menggunakan simple feature scaling
for column in list(data.columns):
  data[column] = data[column]/data[column].max()


In [ ]:
data.sample(5)

times_pregnant  glucose_concentration  blood_pressure  \
78         0.000000               0.658291        0.566438   
146        0.529412               0.286432        0.655738   
172        0.117647               0.437186        0.566438   
116        0.294118               0.623116        0.606557   
93         0.235294               0.673367        0.590164   

     triceps_skin_thickness  serum_insulin  body_mass_index  \
78                 0.207439            0.0         0.643815   
146                0.373737            0.0         0.488823   
172                0.232323            0.0         0.430700   
116                0.207439            0.0         0.506706   
93                 0.207439            0.0         0.354694   

     diabetes_pedigree       age  
78            0.111570  0.320988  
146           0.039669  0.506173  
172           0.319421  0.308642  
116           0.090909  0.469136  
93            0.114463  0.740741

In [ ]:
# Melihat rentang data utk mengetahui apabila scaling berhasil atau tidak, nilai min dan max harus diantara 0 atau 1
for column in list(data.columns):
  print(f"Max value of column {column} is: {round(data[column].max(),3)}")
  print(f"Min value of column {column} is: {round(data[column].min(),3)}")

Max value of column times_pregnant is: 1.0
Min value of column times_pregnant is: 0.0
Max value of column glucose_concentration is: 1.0
Min value of column glucose_concentration is: 0.221
Max value of column blood_pressure is: 1.0
Min value of column blood_pressure is: 0.197
Max value of column triceps_skin_thickness is: 1.0
Min value of column triceps_skin_thickness is: 0.071
Max value of column serum_insulin is: 1.0
Min value of column serum_insulin is: 0.0
Max value of column body_mass_index is: 1.0
Min value of column body_mass_index is: 0.271
Max value of column diabetes_pedigree is: 1.0
Min value of column diabetes_pedigree is: 0.032
Max value of column age is: 1.0
Min value of column age is: 0.259


<h2>Begining Our Machine Learning Logistic Regression</h2>

Changing Our data into an array

In [ ]:
feature_set = data.to_numpy()
label_set = label.to_numpy()

In [ ]:
np.set_printoptions(formatter={'float':'{: 0.1f}'.format})
feature_set

array([[ 0.4,  0.7,  0.6, ...,  0.5,  0.3,  0.6],
       [ 0.1,  0.4,  0.5, ...,  0.4,  0.1,  0.4],
       [ 0.5,  0.9,  0.5, ...,  0.3,  0.3,  0.4],
       ...,
       [ 0.3,  0.6,  0.6, ...,  0.4,  0.1,  0.4],
       [ 0.1,  0.6,  0.5, ...,  0.4,  0.1,  0.6],
       [ 0.1,  0.5,  0.6, ...,  0.5,  0.1,  0.3]])

In [ ]:
label_set

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [ ]:
print(feature_set.shape)
print(label_set.shape)

(768, 8)
(768,)


<h3>Building The Model Using Keras</h3>

In [ ]:
# importing Tensorflow keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# We are going to use Sequential to make the model, Sequential is a deep learning Model
# Then we add neurons (layers) to the Sequential Model

model = Sequential()
# we are using activation = 'sigmoid' because it is a classification problem, sigmoid will plot our data to max value of 1 and min value of 0
# we also add 1 neuron layer to our model with all our features as the input
model.add(Dense(1, input_dim = len(feature_set[0, :]), activation = 'sigmoid'))

In [ ]:
# We also tell the computer that it needs to watch out for binary errors because we are doing a logistic regression with 0 and 1 as an output
model.compile(loss = 'binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
# rmsprop is an optimizer algorithm for Artificial Neural Network
# accuracy is commonly used as the metric to evaluate our model
# all of this is pretty much common Rules of Engangement

In [ ]:
# Now we are going to fit our model, we are going to start training the model
# The verbose argument essential mean that we want to see our machine's learning progress as a progress bar
model.fit(x = feature_set, y= label_set, epochs =512, verbose = 1)

Epoch 1/512
24/24 [==============================] - 1s 2ms/step - loss: 0.8076 - accuracy: 0.3529
Epoch 2/512
24/24 [==============================] - 0s 2ms/step - loss: 0.7823 - accuracy: 0.3568
Epoch 3/512
24/24 [==============================] - 0s 2ms/step - loss: 0.7619 - accuracy: 0.3672
Epoch 4/512
24/24 [==============================] - 0s 2ms/step - loss: 0.7431 - accuracy: 0.3789
Epoch 5/512
24/24 [==============================] - 0s 2ms/step - loss: 0.7270 - accuracy: 0.4049
Epoch 6/512
24/24 [==============================] - 0s 2ms/step - loss: 0.7123 - accuracy: 0.4440
Epoch 7/512
24/24 [==============================] - 0s 2ms/step - loss: 0.6993 - accuracy: 0.4831
Epoch 8/512
24/24 [==============================] - 0s 3ms/step - loss: 0.6885 - accuracy: 0.5404
Epoch 9/512
24/24 [==============================] - 0s 2ms/step - loss: 0.6796 - accuracy: 0.5807
Epoch 10/512
24/24 [==============================] - 0s 2ms/step - loss: 0.6727 - accuracy: 0.6198
Epoch 11/

In [ ]:
# now we test it
# because we did not do a split train and test, we can test it to our training data set (oh well)

# The data that we are going to see
label_set[0:5]

array([1, 0, 1, 0, 1])

In [ ]:
predictions = model.predict(feature_set[0:5])

1/1 [==============================] - 0s 85ms/step


In [ ]:
print(predictions.T)
# we can see the prediction is correct, the confidence is 0.6, 0.1, 0.8, 0.1, 0.8

[[ 0.6  0.2  0.7  0.2  0.7]]
